type TProduction =
  'all'
  | 'worker'
  | 'unemployed'
  | 'women'
  | 'private'
  | 'delinquent'
  | 'small'
  | 'noVisit'
  | 'monthly'
  | 'sameDay'
  | 'business'
  | 'daily'
  | 'lowCredit'
  | 'credit'
  | 'additional'
  | 'car'
  | 'realEstate'
  | 'h24'
  | 'emergency'
  | 'dayLabor'
  | 'freelancer'
  | 'pawn'
  | 'blacklisted'
  | 'housewife'
  | 'rehabBankruptcy'
  | 'refinance'
  | 'other'

export default TProduction