/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Loan API
 * Loan API description
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** 아이디 */
  id: string
  /** 비밀번호 */
  password: string
}
